name: 🛠️ Build & 🚀 Deploy

on:
  # Run on each push to main
  push:
    branches:
      - main

  # Run on each push to a PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: 🛠️ Build
        run: npm run build
        env:
          # Tell Svelte that it'll be hosted in the /portfolio-workshop folder.
          # Remove this if hosting at the domain root.
          SVELTE_BASE_PATH: /${{ github.event.repository.name }}

      - name: Copy index.html to 404.html
        run: |
          cd ./build
          [ -f ./404.html ] || cp ./index.html ./404.html

      - name: Disable default Jekyll integration
        run: touch ./build/.nojekyll

      - name: 🚀 Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
